Switch to a develop branch for the CI and testing

diff --git a/.github/workflows/template-build.yml b/.github/workflows/template-build.yml
--- a/.github/workflows/template-build.yml
+++ b/.github/workflows/template-build.yml
@@ -1,11 +1,8 @@
-# This workflow will build a .NET project
-# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net
-
 name: template-build
 
 on:
   push:
-    branches: [ "master" ]
+    branches: [ "develop" ]
     # paths:
     #   - 'cloudscribeTemplate/**'
     #   - 'Content/**'
@@ -25,11 +22,11 @@ jobs:
       uses: actions/setup-dotnet@v4
       with:
         dotnet-version: 8.0.x
+    - name: Build NuGet package locally and test in at least 6 different configurations
+      run: ./testtemplates.sh || (echo "At least one test failed!" && exit 1)
     - name: Setup NuGet
       run: dotnet nuget add source ${{ secrets.NUGET_SOURCE_URL }} -u ${{secrets.NUGET_USERNAME }} -p ${{ secrets.NUGET_PASSWORD }} --store-password-in-clear-text
-    - name: Build NuGet package and test in at least 6 different configurations
-      run: ./testtemplates.sh || (echo "At least one test failed!" && exit 1)
-    - name: Publish NUGET
+    - name: Publish Template nupkg
       run: dotnet nuget push ./nupkgs/*.nupkg --source ${{ secrets.NUGET_SOURCE_URL }} || (echo "Failed to publish NUGET!" && exit 1)
     - name: Remote Repository Dispatch
       uses: peter-evans/repository-dispatch@v3
